### ISSUE TITLE
Error: EAGAIN: resource temporarily unavailable, read

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/ebi#86]
```
$ ebi --version
1.2.0
```

```
$ http 'https://tako.in.ft.com/tako/repositories?topic=serverless' "Authorization:Bearer $(heroku config:get --app ft-next-tako BEARER_TOKEN)" | jq -r '.repositories[] | "\(.owner)/\(.name)"' | ebi --token $VAULT_AUTH_GITHUB_TOKEN contents app.json
/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at getRepositories (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/lib/get-repositories.js:16:20)
    at Object.exports.handler (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/src/commands/contents.js:50:35)
    at Object.runCommand (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/Users/samuel.parkinson/.nvm/versions/node/v8.15.1/lib/node_modules/ebi/bin/ebi.js:13:32)
    at Module._compile (module.js:653:30)
```

**Comment by sjparkinson** [comment]
https://github.com/Financial-Times/ebi/blob/e59bbae4f28a869cbe2e2bf4295c081caec2e783/lib/get-repositories.js#L16

**Comment by sjparkinson** [comment]
Saving the repositories to a file first and reading straight from the file was okay.

```
$ cat ~/Documents/repos.txt | ebi --token $VAULT_AUTH_GITHUB_TOKEN contents app.json
```

**Comment by taktran** [comment]
Might be related to this: https://stackoverflow.com/questions/40362369/stdin-read-fails-on-some-input

**Comment by sjparkinson** [comment]
> `var n = require('fs').readSync(0, b, 0, b.length);`
> 
> I think (pure conjecture) that process.stdin.fd is a getter that, when referenced, will put stdin in non-blocking mode (which is causing the error). When you use the file descriptor directly, you work around that.

Seems like an okay thing to hardcode 👌. Nice find.

**Comment by taktran** [comment]
Actually, using [readline](https://nodejs.org/api/readline.html) seems like a cleaner solution
