### ISSUE TITLE
Error when there are no repos specified

### ISSUE THREAD

**Issue by taktran** [Financial-Times/ebi#90]
When there are no repos specified, an error is shown eg,

```
$ ./bin/ebi.js package
ebi.js package [search] [repo..]

Search within the `package.json` file

...

TypeError: Cannot read property 'map' of undefined
    at getRepositories (/Users/ttt/Work/Dev/FT/ebi/lib/get-repositories.js:22:4)
    at Object.exports.handler (/Users/ttt/Work/Dev/FT/ebi/src/commands/package.js:44:41)
    at Object.runCommand (/Users/ttt/Work/Dev/FT/ebi/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/ttt/Work/Dev/FT/ebi/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/Users/ttt/Work/Dev/FT/ebi/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/Users/ttt/Work/Dev/FT/ebi/bin/ebi.js:13:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

Can have a better error message eg, "No repositories are provided, please specify some either in standard input or at the end"

Might be easier to do when https://github.com/Financial-Times/ebi/issues/86 is fixed

**Comment by taktran** [comment]
Or could just output nothing ie,

```
$ ./bin/ebi.js package
$
```

**Comment by taktran** [comment]
This is fixed by https://github.com/Financial-Times/ebi/pull/91, by outputting nothing (ie, https://github.com/Financial-Times/ebi/issues/90#issuecomment-490146830). I think this is ok for now.
